---
production: &default
  serverPort: 3333
  baseUrl: http://www.makingdevelopers.com
  views:
    engine: .hbs
    extension: .hbs
    layout: main
  html:
    livereload: false
    minify: true
    css:
      stylusPrecompile: true
      compress: true
  app:
    default: blog
  languages:
    default: en
    list: [en, es, jp]
  security:
    secret: santoysena.com
  session:
    cookieDomain: localhost.cms
    maxAge: 259200
    cookiePrefix: 'mdSession_'
    path: '/'
    httpOnly: true

stage: &stage
  <<: *default
  baseUrl: http://stage.makingdevelopers.com

latest: &latest
  <<: *stage
  baseUrl: http://latest.makingdevelopers.com

development:
  <<: *latest
  baseUrl: http://local.makingdevelopers.com
  html:
    livereload: true
    minify: false
    css:
      stylusPrecompile: false
      compress: false
